spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CloudNote?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: cf15203689690.
  servlet:
    multipart:
      max-file-size: 5MB
  elasticsearch:
    uris: http://localhost:9200



mybatis:
  type-aliases-package: com.liang.pojo
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false


#操作oss需要的一些参数
aliyun:
  accessKeyId: LTAI5tKe3Bnt3hY3hm6jzd5z       # 阿里云的accessKeyId
  secretAccessKey: D1XncWLHDcHDj6gp0zsGraZgNTzgSC   # accessKey 密码
  oss:
    endPoint: oss-cn-hangzhou.aliyuncs.com     # Endpoint:在阿里云oss控制台查看自己使用的endpoint
    bucketName: lcloudnote   # bucket 名称

elasticsearch:
  host: localhost
  port: 9200

#yml配置
logging:
  config: classpath:log/logback-spring.xml
  level:
    root: info
  file:
    path: ./log
